name = "ProceduralNoise"
uuid = "3e47a1cc-29f2-4c46-afe0-95fe1d251308"
authors = ["Cédric Belmant"]
version = "0.1.0"

[compat]
julia = "1.4.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
